package com.github.naios.wide.core.framework.game;

public enum Races
{
    RACE_NONE,
    RACE_HUMAN,
    RACE_ORC,
    RACE_DWARF,
    RACE_NIGHTELF,
    RACE_UNDEAD_PLAYER5,
    RACE_TAUREN,
    RACE_GNOME7,
    RACE_TROLL,
    RACE_GOBLIN9,
    RACE_BLOODELF,
    RACE_DRAENEI,
    RACE_FEL_ORC,
    RACE_NAGA13,
    RACE_BROKEN,
    RACE_SKELETON,
    RACE_VRYKUL,
    RACE_TUSKARR,
    RACE_FOREST_TROLL,
    RACE_TAUNKA,
    RACE_NORTHREND_SKELETON,
    RACE_ICE_TROLL,
    RACE_WORGEN,
    RACE_GILNEAN,
    RACE_PANDAREN_NEUTRAL,
    RACE_PANDAREN_ALLIANCE,
    RACE_PANDAREN_HORDE;
}
